import {
  ArrowLeft, ArrowRight, BarChart3, Box, Boxes, Calendar, Check, CheckCircle2,
  ChevronDown, ChevronLeft, ChevronRight, CircleAlert, ClipboardList, Clock,
  CloudUpload, Crown, Download, File, FileImage,
  FileText, Hash, Info, Layers, LayoutDashboard, ListFilter, LogOut, Menu, MessageCircle,
  MessageSquarePlus, Minus, PackageCheck, Palette, PartyPopper, Paperclip, PencilLine,
  PenTool, Phone, Plus, PlusCircle, Printer, Receipt, ReceiptText, Ruler, Search,
  Tag, TrendingUp, TriangleAlert, Trash2, Trophy, User, UserCog, Wallet, X,
  type LucideProps,
} from "lucide-react"
import type { ComponentType } from "react"

const REGISTRY: Record<string, ComponentType<LucideProps>> = {
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "bar-chart-3": BarChart3,
  box: Box,
  boxes: Boxes,
  calendar: Calendar,
  check: Check,
  "check-circle-2": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-alert": CircleAlert,
  "clipboard-list": ClipboardList,
  clock: Clock,
  "cloud-upload": CloudUpload,
  crown: Crown,
  download: Download,
  file: File,
  "file-image": FileImage,
  "file-text": FileText,
  hash: Hash,
  info: Info,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "list-filter": ListFilter,
  "log-out": LogOut,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square-plus": MessageSquarePlus,
  minus: Minus,
  "package-check": PackageCheck,
  palette: Palette,
  "party-popper": PartyPopper,
  paperclip: Paperclip,
  "pencil-line": PencilLine,
  "pen-tool": PenTool,
  phone: Phone,
  plus: Plus,
  "plus-circle": PlusCircle,
  printer: Printer,
  receipt: Receipt,
  "receipt-text": ReceiptText,
  ruler: Ruler,
  search: Search,
  tag: Tag,
  "trending-up": TrendingUp,
  "triangle-alert": TriangleAlert,
  "trash-2": Trash2,
  trophy: Trophy,
  user: User,
  "user-cog": UserCog,
  wallet: Wallet,
  x: X,
}

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Cmp = REGISTRY[name] ?? Box
  return <Cmp {...props} />
}
